### ISSUE TITLE
Move to Twitter API v2

### ISSUE THREAD

**Issue by mesaugat** [mesaugat/bikram-sambat-progress#2]
Twitter might deprecate the v1 API soon. Status updates don't work right now. 😢 Need to move of off API v1 and start using API v2.

```
twitter: 453 You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level.
```

Tasks to do:

- Replace current github.com/dghubble/go-twitter with something that uses Twitter API v2
- Test the changes out

**Comment by silwalanish** [comment]
It's not Twitter anymore. It's `X`.
